#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibonacci_sequence = [1, 2]
aux = fibonacci_sequence[0] + fibonacci_sequence[1]

while aux < 4_000_000
  fibonacci_sequence << aux
  aux = fibonacci_sequence[fibonacci_sequence.length - 2] +
        fibonacci_sequence[fibonacci_sequence.length - 1]
end

puts fibonacci_sequence.inspect
puts fibonacci_sequence.inject(0) { |memo, n| 
  (n % 2 == 0) ? memo + n : memo
}

